version: "3.8"
services:
  airflow:
    image: apache/airflow:2.9.2
    restart: unless-stopped
    env_file:
      - .env.aws
    environment:
      SQL_DIR: /opt/airflow/sql                # ← 동일
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__PARALLELISM: "2"
      AIRFLOW__CORE__DAG_CONCURRENCY: "2"
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "1"
      AIRFLOW__SCHEDULER__MAX_THREADS: "2"
      AIRFLOW__WEBSERVER__WORKERS: "1"
      AIRFLOW__CONNECTIONS__POSTGRES_DEFAULT: ${AIRFLOW_CONN_POSTGRES_DEFAULT}
    volumes:
      - /home/ubuntu/olist-pipeline/dag:/opt/airflow/dags
      - /home/ubuntu/olist-pipeline/sql:/opt/airflow/sql
    ports: ["8080:8080"]
    command: >
      bash -lc "airflow db init &&
      airflow users create --username admin --password admin --firstname a --lastname a --role Admin --email a@a.a || true &&
      airflow webserver & airflow scheduler"
